services:
  spark-master:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-master
    hostname: spark-master
    entrypoint: ["/bin/bash", "-c", "/opt/spark/sbin/start-connect-server.sh && exec /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"]
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: "7077"
      SPARK_MASTER_WEBUI_PORT: "8080"
    ports:
      - "15002:15002" # Spark Connect RPC Port
      - "8080:8080"   # Master Web UI
      - "7077:7077"   # Master port (workers/clients connect here)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-worker-1
    hostname: spark-worker-1
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_WORKER_WEBUI_PORT: "8081"
    ports:
      - "8081:8081"   # Worker 1 Web UI
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-worker-2
    hostname: spark-worker-2
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_WORKER_WEBUI_PORT: "8082"
    ports:
      - "8082:8082"   # Worker 2 Web UI
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - spark-net

  spark-worker-3:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-worker-3
    hostname: spark-worker-3
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_WORKER_WEBUI_PORT: "8083"
    ports:
      - "8083:8083"   # Worker 3 Web UI
    depends_on:
      spark-master:
        condition: service_healthy
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
